#endpoint: http://www.swzooproject.org/vu-group-10/

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX swz: <http://www.swzooproject.org/vu-group-10/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX db: <http://dbpedia.org/>

Construct {
  ?AnimalSpecie a ?phylum;
    rdfs:label ?label;
    dbo:abstract ?abstract.
  ?phylum rdfs:subClassOf dbo:Mollusca;
             rdfs:label ?phylumLabel;
  		dbo:abstract ?phylumAbstract.

}
  
WHERE {
  ?AnimalSpecie dbo:class ?phylum ;
      rdfs:label ?label;
  	dbo:abstract ?abstract.
	?phylum dbo:phylum dbr:Mollusca;
         rdfs:label ?phylumLabel;
  		dbo:abstract ?phylumAbstract.
  FILTER (lang(?label) = 'nl')
  FILTER (lang(?abstract) = 'nl')
  FILTER (lang(?phylumLabel) = 'nl')
  FILTER (lang(?phylumAbstract) = 'nl')
} 


  
  